const std = @import("std");

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addStaticLibrary(.{
        .name = "mbedtls",
        .target = target,
        .optimize = optimize,
    });
    lib.linkLibC();
    lib.addCSourceFiles(.{ .files = sources, .flags = &.{} });
    lib.addIncludePath(.{ .path = "library" });
    lib.addIncludePath(.{ .path = "include" });
    b.installArtifact(lib);
}

const sources = &[_][]const u8{
    "library/ecjpake.c",
    "library/bignum_mod_raw.c",
    "library/sha1.c",
    "library/ecdh.c",
    "library/sha512.c",
    "library/mps_reader.c",
    "library/aesce.c",
    "library/psa_crypto_ffdh.c",
    "library/cmac.c",
    "library/dhm.c",
    "library/ssl_ticket.c",
    "library/ccm.c",
    "library/x509_crl.c",
    "library/sha3.c",
    "library/psa_crypto_se.c",
    "library/x509.c",
    "library/psa_crypto_mac.c",
    "library/nist_kw.c",
    "library/rsa.c",
    "library/debug.c",
    "library/x509_crt.c",
    "library/psa_crypto_rsa.c",
    "library/sha256.c",
    "library/ecp_curves_new.c",
    "library/pkcs12.c",
    "library/x509_create.c",
    "library/bignum_mod.c",
    "library/chacha20.c",
    "library/mps_trace.c",
    "library/hkdf.c",
    "library/ssl_tls12_server.c",
    "library/psa_crypto.c",
    "library/x509_csr.c",
    "library/cipher_wrap.c",
    "library/ssl_ciphersuites.c",
    "library/asn1write.c",
    "library/constant_time.c",
    "library/psa_crypto_ecp.c",
    "library/memory_buffer_alloc.c",
    "library/timing.c",
    "library/psa_crypto_pake.c",
    "library/ecp.c",
    "library/rsa_alt_helpers.c",
    "library/pem.c",
    "library/threading.c",
    "library/pkparse.c",
    "library/poly1305.c",
    "library/x509write.c",
    "library/psa_crypto_slot_management.c",
    "library/aesni.c",
    "library/pkcs7.c",
    "library/ssl_cookie.c",
    "library/cipher.c",
    "library/ctr_drbg.c",
    "library/psa_crypto_aead.c",
    "library/oid.c",
    "library/ssl_tls13_keys.c",
    "library/x509write_csr.c",
    "library/psa_crypto_storage.c",
    "library/ecdsa.c",
    "library/ecp_curves.c",
    "library/ssl_msg.c",
    "library/ripemd160.c",
    "library/camellia.c",
    "library/aria.c",
    "library/asn1parse.c",
    "library/lms.c",
    "library/net_sockets.c",
    "library/des.c",
    "library/ssl_tls13_generic.c",
    "library/pkcs5.c",
    "library/psa_its_file.c",
    "library/entropy.c",
    "library/entropy_poll.c",
    "library/ssl_cache.c",
    "library/chachapoly.c",
    "library/padlock.c",
    "library/psa_crypto_hash.c",
    "library/version.c",
    "library/psa_crypto_cipher.c",
    "library/x509write_crt.c",
    "library/hmac_drbg.c",
    "library/bignum_core.c",
    "library/platform_util.c",
    "library/psa_util.c",
    "library/gcm.c",
    "library/pk.c",
    "library/base64.c",
    "library/ssl_client.c",
    "library/pk_ecc.c",
    "library/ssl_tls12_client.c",
    "library/ssl_tls13_client.c",
    "library/psa_crypto_client.c",
    "library/bignum.c",
    "library/block_cipher.c",
    "library/lmots.c",
    "library/ssl_tls13_server.c",
    "library/pk_wrap.c",
    "library/ssl_tls.c",
    "library/md.c",
    "library/aes.c",
    "library/platform.c",
    "library/md5.c",
    "library/pkwrite.c",
};
